import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import Image from 'next/image';
import React from 'react'; 
import { TbCodeDots } from "react-icons/tb";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen overflow-hidden bg-primary">
          <ToastContainer
            position="top-right"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
          <header className="bg-white py-4 px-40">
            <div className="max-w-screen-xxl mx-auto flex items-center">
              <Image
                src="/PricewaterhouseCoopers_Logo.png"
                alt="PwC Logo"
                width={75}
                height={25} 
                className="mr-3"
              />
              <div className="border-l-2 border-primary h-8 mx-5"></div>
              <span className="text-2xl text-primary font-medium"><TbCodeDots fontSize={"2.2rem"}/></span>
            </div>
          </header>
          <main className="flex-grow overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
